# Dynamic configuration
http:
  routers:
    uptimer:
      rule: "Host(`{{ env \"DOMAIN\" }}`)"
      entryPoints:
        - websecure
      service: uptimer
      tls:
        certResolver: letsencrypt
        domains:
          - main: "{{ env \"DOMAIN\" }}"
            sans:
              - "{{ env \"WILDCARD_DOMAIN\" }}"

  services:
    uptimer:
      loadBalancer:
        servers:
          - url: "http://up-timer:80"
